# Site settings
title: Example Code
email: chengkai.me@gmail.com
description: "关于我：自由懒散的程序员一枚，因为懒，所以喜欢极简主义，憎恨一切形式化的东西。不喜欢写BLOG，直到遇见了Jekyll，让我感到写文章有写代码的感觉"
baseurl: ""
url: "http://examplecode.github.io"

versioin: 1.0

# Build settings
markdown: kramdown
permalink: pretty
